# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NaviSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NaviSample
	pod 'RxSwift', '~> 3.0'
    pod 'SwiftProtobuf', git: 'https://github.com/apple/swift-protobuf.git', :tag => '0.9.902'
    pod 'Alamofire', '~> 4.4'
    pod 'AlamofireObjectMapper', '~> 4.0'
    project './NaviSample'
    
    pod 'Toast-Swift', '~> 2.0.0'
    pod 'Kingfisher', '~> 3.0'
end
